apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-service
  namespace: microservices
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-service
  template:
    metadata:
      labels:
        app: frontend-service
    spec:
      containers:
        - name: nginx
          image: your-registry/frontend-service:latest
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: microservices
spec:
  selector:
    app: frontend-service
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
