apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-service
  namespace: microservices
spec:
  replicas: 2
  selector:
    matchLabels:
      app: worker-service
  template:
    metadata:
      labels:
        app: worker-service
    spec:
      containers:
        - name: worker
          image: your-registry/worker-service:latest
          env:
            - name: DATABASE_URL
              value: postgresql://postgres:postgres@postgres:5432/mydb
            - name: QUEUE_URL
              value: redis://redis:6379/0
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
