# Use Python base image
FROM python:3.11-slim

# Set working directory
WORKDIR /usr/src/app

# Copy requirements
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy source code
COPY src ./src

# Run worker
CMD ["python", "src/worker.py"]

